blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://getsphere.dev/discord
    about: If you have a "How do I?" question please ask in the our Discord (https://getsphere.dev/discord)